CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FirstName" text,
    "LastName" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "CompanyName" text,
    "PhoneNumber" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Contacts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "ArabicName" character varying(100) NOT NULL,
    "EnglishName" character varying(100) NOT NULL,
    "FormattedPhone" character varying(100) NOT NULL,
    "Gender" character varying(1) NOT NULL,
    "Status" integer NOT NULL,
    "IssueDescription" character varying(500),
    "LastMessageSentAt" timestamp with time zone,
    "LastStatusUpdateAt" timestamp with time zone,
    "SendAttemptCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "ApiKeyId" character varying(450) NOT NULL,
    "UserId" character varying(450) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Number" character varying(20) NOT NULL,
    CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id")
);

CREATE TABLE "SubscriptionPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "MaxMessagesPerDay" integer NOT NULL,
    "MaxApiKeys" integer NOT NULL,
    "MaxCampaignTemplates" integer NOT NULL,
    "MaxContactsPerCampaign" integer NOT NULL,
    "HasPrioritySupport" boolean NOT NULL,
    "HasCustomIntegrations" boolean NOT NULL,
    "HasAdvancedAnalytics" boolean NOT NULL,
    "HasScheduledMessages" boolean NOT NULL,
    "HasTemplateVariables" boolean NOT NULL,
    "HasMultiLanguageSupport" boolean NOT NULL,
    "HasWhatsAppBotIntegration" boolean NOT NULL,
    "HasCustomBranding" boolean NOT NULL,
    "TrialDurationDays" integer NOT NULL,
    "BillingCycleDays" integer NOT NULL,
    "GracePeriodDays" integer NOT NULL,
    "DiscountPercentage" numeric,
    "DiscountValidUntil" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY ("Id")
);

CREATE TABLE "SystemSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(100) NOT NULL,
    "Value" text NOT NULL,
    "Description" character varying(500),
    "Category" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" text,
    CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CampaignTemplates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "MessageTemplate" text NOT NULL,
    "MaleContent" text,
    "FemaleContent" text,
    "AutoGenerateGenderVersions" boolean NOT NULL,
    "Category" character varying(50) NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsGlobal" boolean NOT NULL,
    "IsSystemTemplate" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "HasAttachment" boolean NOT NULL,
    "AttachmentPath" text,
    "AttachmentName" text,
    "AttachmentType" text,
    "SupportsVariables" boolean NOT NULL,
    "AvailableVariables" text,
    "IsScheduled" boolean NOT NULL,
    "ScheduledAt" timestamp with time zone,
    "ScheduleRecurrence" text,
    "LastScheduledRun" timestamp with time zone,
    "NextScheduledRun" timestamp with time zone,
    "SupportsMultiLanguage" boolean NOT NULL,
    "DefaultLanguage" character varying(10),
    "TranslatedTemplates" text,
    "TimesUsed" integer NOT NULL,
    "LastUsedAt" timestamp with time zone,
    "SuccessRate" numeric NOT NULL,
    "TargetAudience" text,
    "MaxRecipientsPerBatch" integer,
    CONSTRAINT "PK_CampaignTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CampaignTemplates_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UsageStatistics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "MessagesSent" integer NOT NULL,
    "MessagesDelivered" integer NOT NULL,
    "MessagesFailed" integer NOT NULL,
    "TotalCost" numeric(10,4) NOT NULL,
    "ApiCallsMade" integer NOT NULL,
    CONSTRAINT "PK_UsageStatistics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UsageStatistics_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ApiKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Key" character varying(64) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "SubscriptionPlanId" integer NOT NULL,
    "DailyQuotaUsed" integer NOT NULL,
    "TotalMessagesUsed" integer NOT NULL,
    "LastUsedAt" timestamp with time zone,
    "LastUsageResetAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone,
    "RevokedAt" timestamp with time zone,
    CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ApiKeys_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ApiKeys_SubscriptionPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "MessageTimingControls" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "MinDelaySeconds" integer NOT NULL,
    "MaxDelaySeconds" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "SubscriptionPlanId" integer,
    CONSTRAINT "PK_MessageTimingControls" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MessageTimingControls_SubscriptionPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RandomDelayRules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "AfterMessageCount" integer NOT NULL,
    "PauseDurationMinutes" integer NOT NULL,
    "RandomVarianceSeconds" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "Description" character varying(500),
    "Priority" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "SubscriptionPlanId" integer,
    CONSTRAINT "PK_RandomDelayRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RandomDelayRules_SubscriptionPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserSubscriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "SubscriptionPlanId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "AmountPaid" numeric(18,2) NOT NULL,
    "PaymentMethod" text NOT NULL,
    "PaymentReference" text,
    "IsActive" boolean NOT NULL,
    "AutoRenew" boolean NOT NULL,
    "IsTrialPeriod" boolean NOT NULL,
    "IsInGracePeriod" boolean NOT NULL,
    "Status" character varying(50) NOT NULL,
    "NextBillingDate" timestamp with time zone,
    "TrialEndsAt" timestamp with time zone,
    "GracePeriodEndsAt" timestamp with time zone,
    "CurrentPeriodMessages" integer NOT NULL,
    "LastUsageResetAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CancelledAt" timestamp with time zone,
    "CancellationReason" text,
    "CancelledBy" text,
    CONSTRAINT "PK_UserSubscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserSubscriptions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserSubscriptions_SubscriptionPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "VideoTimingControls" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "MinDelayBeforeUploadSeconds" integer NOT NULL,
    "MaxDelayBeforeUploadSeconds" integer NOT NULL,
    "MinUploadTimeSeconds" integer NOT NULL,
    "MaxUploadTimeSeconds" integer NOT NULL,
    "MinDelayAfterUploadSeconds" integer NOT NULL,
    "MaxDelayAfterUploadSeconds" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "SubscriptionPlanId" integer,
    CONSTRAINT "PK_VideoTimingControls" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VideoTimingControls_SubscriptionPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MessageHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Phone" character varying(20) NOT NULL,
    "MessageContent" text NOT NULL,
    "Status" character varying(50) NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "ErrorMessage" text,
    "HasAttachment" boolean NOT NULL,
    "AttachmentName" text,
    "AttachmentType" text,
    "AttachmentSize" bigint,
    "ApiKeyUsed" text,
    "CampaignId" integer,
    "Cost" numeric(10,4),
    CONSTRAINT "PK_MessageHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MessageHistory_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MessageHistory_CampaignTemplates_CampaignId" FOREIGN KEY ("CampaignId") REFERENCES "CampaignTemplates" ("Id")
);

CREATE TABLE "TemplateAttachments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CampaignTemplateId" integer NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "FilePath" character varying(255) NOT NULL,
    "ContentType" character varying(100) NOT NULL,
    "FileSize" bigint NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TemplateAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TemplateAttachments_CampaignTemplates_CampaignTemplateId" FOREIGN KEY ("CampaignTemplateId") REFERENCES "CampaignTemplates" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PaymentTransactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "SubscriptionId" integer,
    "Amount" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "PaymentMethod" character varying(50) NOT NULL,
    "PaymentReference" text,
    "PaymentGatewayResponse" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentTransactions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PaymentTransactions_UserSubscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES "UserSubscriptions" ("Id")
);

INSERT INTO "SubscriptionPlans" ("Id", "BillingCycleDays", "CreatedAt", "Description", "DiscountPercentage", "DiscountValidUntil", "DisplayOrder", "GracePeriodDays", "HasAdvancedAnalytics", "HasCustomBranding", "HasCustomIntegrations", "HasMultiLanguageSupport", "HasPrioritySupport", "HasScheduledMessages", "HasTemplateVariables", "HasWhatsAppBotIntegration", "IsActive", "MaxApiKeys", "MaxCampaignTemplates", "MaxContactsPerCampaign", "MaxMessagesPerDay", "Name", "Price", "TrialDurationDays", "UpdatedAt")
VALUES (1, 30, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Try our service free for 14 days - no credit card required', NULL, NULL, 1, 3, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 1, 3, 25, 50, 'Free Trial', 0.0, 14, NULL);
INSERT INTO "SubscriptionPlans" ("Id", "BillingCycleDays", "CreatedAt", "Description", "DiscountPercentage", "DiscountValidUntil", "DisplayOrder", "GracePeriodDays", "HasAdvancedAnalytics", "HasCustomBranding", "HasCustomIntegrations", "HasMultiLanguageSupport", "HasPrioritySupport", "HasScheduledMessages", "HasTemplateVariables", "HasWhatsAppBotIntegration", "IsActive", "MaxApiKeys", "MaxCampaignTemplates", "MaxContactsPerCampaign", "MaxMessagesPerDay", "Name", "Price", "TrialDurationDays", "UpdatedAt")
VALUES (2, 30, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Perfect for small businesses getting started with WhatsApp marketing', NULL, NULL, 2, 3, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, 2, 10, 100, 100, 'Starter', 9.99, 7, NULL);
INSERT INTO "SubscriptionPlans" ("Id", "BillingCycleDays", "CreatedAt", "Description", "DiscountPercentage", "DiscountValidUntil", "DisplayOrder", "GracePeriodDays", "HasAdvancedAnalytics", "HasCustomBranding", "HasCustomIntegrations", "HasMultiLanguageSupport", "HasPrioritySupport", "HasScheduledMessages", "HasTemplateVariables", "HasWhatsAppBotIntegration", "IsActive", "MaxApiKeys", "MaxCampaignTemplates", "MaxContactsPerCampaign", "MaxMessagesPerDay", "Name", "Price", "TrialDurationDays", "UpdatedAt")
VALUES (3, 30, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Ideal for growing businesses with moderate messaging needs', NULL, NULL, 3, 5, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, 5, 25, 500, 500, 'Professional', 29.99, 7, NULL);
INSERT INTO "SubscriptionPlans" ("Id", "BillingCycleDays", "CreatedAt", "Description", "DiscountPercentage", "DiscountValidUntil", "DisplayOrder", "GracePeriodDays", "HasAdvancedAnalytics", "HasCustomBranding", "HasCustomIntegrations", "HasMultiLanguageSupport", "HasPrioritySupport", "HasScheduledMessages", "HasTemplateVariables", "HasWhatsAppBotIntegration", "IsActive", "MaxApiKeys", "MaxCampaignTemplates", "MaxContactsPerCampaign", "MaxMessagesPerDay", "Name", "Price", "TrialDurationDays", "UpdatedAt")
VALUES (4, 30, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'For large businesses with high-volume messaging requirements', NULL, NULL, 4, 7, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 10, 100, 2000, 2000, 'Business', 99.99, 14, NULL);
INSERT INTO "SubscriptionPlans" ("Id", "BillingCycleDays", "CreatedAt", "Description", "DiscountPercentage", "DiscountValidUntil", "DisplayOrder", "GracePeriodDays", "HasAdvancedAnalytics", "HasCustomBranding", "HasCustomIntegrations", "HasMultiLanguageSupport", "HasPrioritySupport", "HasScheduledMessages", "HasTemplateVariables", "HasWhatsAppBotIntegration", "IsActive", "MaxApiKeys", "MaxCampaignTemplates", "MaxContactsPerCampaign", "MaxMessagesPerDay", "Name", "Price", "TrialDurationDays", "UpdatedAt")
VALUES (5, 30, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Unlimited messaging for enterprise-level operations with dedicated support', NULL, NULL, 5, 14, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 25, -1, 10000, 10000, 'Enterprise', 299.99, 14, NULL);

INSERT INTO "SystemSettings" ("Id", "Category", "Description", "Key", "UpdatedAt", "UpdatedBy", "Value")
VALUES (1, 'General', 'The name of the SaaS platform', 'SAAS_NAME', TIMESTAMPTZ '2025-10-29T17:44:38.937324Z', NULL, 'WhatsApp SaaS Platform');
INSERT INTO "SystemSettings" ("Id", "Category", "Description", "Key", "UpdatedAt", "UpdatedBy", "Value")
VALUES (2, 'WhatsApp', 'Base URL for WhatsApp API service', 'WHATSAPP_API_URL', TIMESTAMPTZ '2025-10-29T17:44:38.937359Z', NULL, 'https://localhost:7001/api');
INSERT INTO "SystemSettings" ("Id", "Category", "Description", "Key", "UpdatedAt", "UpdatedBy", "Value")
VALUES (3, 'Billing', 'Cost per message in USD', 'MESSAGE_COST_PER_UNIT', TIMESTAMPTZ '2025-10-29T17:44:38.93736Z', NULL, '0.05');
INSERT INTO "SystemSettings" ("Id", "Category", "Description", "Key", "UpdatedAt", "UpdatedBy", "Value")
VALUES (4, 'General', 'Default timezone for the application', 'DEFAULT_TIMEZONE', TIMESTAMPTZ '2025-10-29T17:44:38.93736Z', NULL, 'UTC');
INSERT INTO "SystemSettings" ("Id", "Category", "Description", "Key", "UpdatedAt", "UpdatedBy", "Value")
VALUES (5, 'WhatsApp', 'Maximum file upload size in bytes (10MB)', 'MAX_FILE_UPLOAD_SIZE', TIMESTAMPTZ '2025-10-29T17:44:38.93736Z', NULL, '10485760');

CREATE UNIQUE INDEX "IX_ApiKeys_Key" ON "ApiKeys" ("Key");

CREATE INDEX "IX_ApiKeys_SubscriptionPlanId" ON "ApiKeys" ("SubscriptionPlanId");

CREATE INDEX "IX_ApiKeys_UserId_IsActive" ON "ApiKeys" ("UserId", "IsActive");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_CampaignTemplates_UserId" ON "CampaignTemplates" ("UserId");

CREATE INDEX "IX_Contacts_ApiKeyId" ON "Contacts" ("ApiKeyId");

CREATE INDEX "IX_Contacts_FormattedPhone" ON "Contacts" ("FormattedPhone");

CREATE INDEX "IX_Contacts_Status" ON "Contacts" ("Status");

CREATE INDEX "IX_Contacts_UserId" ON "Contacts" ("UserId");

CREATE INDEX "IX_MessageHistory_CampaignId" ON "MessageHistory" ("CampaignId");

CREATE INDEX "IX_MessageHistory_UserId_SentAt" ON "MessageHistory" ("UserId", "SentAt");

CREATE INDEX "IX_MessageTimingControls_IsActive" ON "MessageTimingControls" ("IsActive");

CREATE INDEX "IX_MessageTimingControls_SubscriptionPlanId" ON "MessageTimingControls" ("SubscriptionPlanId");

CREATE INDEX "IX_PaymentTransactions_SubscriptionId" ON "PaymentTransactions" ("SubscriptionId");

CREATE INDEX "IX_PaymentTransactions_UserId" ON "PaymentTransactions" ("UserId");

CREATE INDEX "IX_RandomDelayRules_IsActive" ON "RandomDelayRules" ("IsActive");

CREATE INDEX "IX_RandomDelayRules_Priority" ON "RandomDelayRules" ("Priority");

CREATE INDEX "IX_RandomDelayRules_SubscriptionPlanId" ON "RandomDelayRules" ("SubscriptionPlanId");

CREATE UNIQUE INDEX "IX_SystemSettings_Key" ON "SystemSettings" ("Key");

CREATE INDEX "IX_TemplateAttachments_CampaignTemplateId" ON "TemplateAttachments" ("CampaignTemplateId");

CREATE UNIQUE INDEX "IX_UsageStatistics_UserId_Date" ON "UsageStatistics" ("UserId", "Date");

CREATE INDEX "IX_UserSubscriptions_SubscriptionPlanId" ON "UserSubscriptions" ("SubscriptionPlanId");

CREATE INDEX "IX_UserSubscriptions_UserId" ON "UserSubscriptions" ("UserId");

CREATE INDEX "IX_VideoTimingControls_IsActive" ON "VideoTimingControls" ("IsActive");

CREATE INDEX "IX_VideoTimingControls_SubscriptionPlanId" ON "VideoTimingControls" ("SubscriptionPlanId");

SELECT setval(
    pg_get_serial_sequence('"SubscriptionPlans"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "SubscriptionPlans") + 1,
        nextval(pg_get_serial_sequence('"SubscriptionPlans"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"SystemSettings"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "SystemSettings") + 1,
        nextval(pg_get_serial_sequence('"SystemSettings"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251029174442_InitialCreate', '9.0.0');

ALTER TABLE "MessageHistory" ADD "CampaignId1" integer;

ALTER TABLE "Contacts" ADD "CampaignId" integer;

CREATE TABLE "Campaigns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "UserId" text NOT NULL,
    "CampaignTemplateId" integer,
    "Status" integer NOT NULL,
    "TotalContacts" integer NOT NULL,
    "MessagesSent" integer NOT NULL,
    "MessagesDelivered" integer NOT NULL,
    "MessagesFailed" integer NOT NULL,
    "CurrentProgress" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StartedAt" timestamp with time zone,
    "PausedAt" timestamp with time zone,
    "StoppedAt" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "LastError" text,
    "ErrorCount" integer NOT NULL,
    "MessageContent" text,
    "UseGenderTemplates" boolean NOT NULL,
    CONSTRAINT "PK_Campaigns" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Campaigns_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Campaigns_CampaignTemplates_CampaignTemplateId" FOREIGN KEY ("CampaignTemplateId") REFERENCES "CampaignTemplates" ("Id") ON DELETE SET NULL
);

UPDATE "SystemSettings" SET "UpdatedAt" = TIMESTAMPTZ '2025-10-29T19:04:01.115094Z'
WHERE "Id" = 1;

UPDATE "SystemSettings" SET "UpdatedAt" = TIMESTAMPTZ '2025-10-29T19:04:01.115121Z'
WHERE "Id" = 2;

UPDATE "SystemSettings" SET "UpdatedAt" = TIMESTAMPTZ '2025-10-29T19:04:01.115121Z'
WHERE "Id" = 3;

UPDATE "SystemSettings" SET "UpdatedAt" = TIMESTAMPTZ '2025-10-29T19:04:01.115122Z'
WHERE "Id" = 4;

UPDATE "SystemSettings" SET "UpdatedAt" = TIMESTAMPTZ '2025-10-29T19:04:01.115122Z'
WHERE "Id" = 5;

CREATE INDEX "IX_MessageHistory_CampaignId1" ON "MessageHistory" ("CampaignId1");

CREATE INDEX "IX_Contacts_CampaignId" ON "Contacts" ("CampaignId");

CREATE INDEX "IX_Campaigns_CampaignTemplateId" ON "Campaigns" ("CampaignTemplateId");

CREATE INDEX "IX_Campaigns_CreatedAt" ON "Campaigns" ("CreatedAt");

CREATE INDEX "IX_Campaigns_UserId_Status" ON "Campaigns" ("UserId", "Status");

ALTER TABLE "Contacts" ADD CONSTRAINT "FK_Contacts_Campaigns_CampaignId" FOREIGN KEY ("CampaignId") REFERENCES "Campaigns" ("Id") ON DELETE SET NULL;

ALTER TABLE "MessageHistory" ADD CONSTRAINT "FK_MessageHistory_Campaigns_CampaignId1" FOREIGN KEY ("CampaignId1") REFERENCES "Campaigns" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251029190402_AddCampaignTable', '9.0.0');

COMMIT;

